INSERT INTO SECURITY_FUNCTIONALROLE (FUNCTIONALROLEID, CODE, NAME, DEPARTMENT, ROLE, USERTYPE, ISREADWRITE, ISACTIVE, CREATEDBY, CREATEDON, UPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 'ADMIN', 'Administrator', 'IT', 'ADMIN', 'EMPLOYEE', 1, 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_GROUP (GROUPID, CODE, NAME, ISACTIVE, CREATEDBY, CREATEDON, UPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 'GRP1', 'Group One', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_GROUPMAP (GROUPMAPID, GROUPID, GROUPMAPVALUE, GROUPMAPDESC, EXCLUDE, SORT, ISACTIVE, CREATEDBY, CREATEDON, UPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 1, 'MAP1', 'Map Desc', 0, 1, 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_FUNCTIONALROLEXREF (FUNCTIONALROLEXREFID, FUNCTIONALROLEID, XREFVALUE, ISACTIVE, CREATEDBY, CREATEDON, UPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 1, 'XREF1', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_USERENTITLEMENTXREF (USERENTITLEMENTXREFID, USERID, ENTITLEMENTID, ISACTIVE, CREATEDBY, CREATEDON, LASTUPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 'user1', 1, 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_USERENTXREFHIST (USERENTITLEMENTXREFHISTID, USERENTITLEMENTXREFID, USERID, ENTITLEMENTID, ISACTIVE, CREATEDBY, CREATEDON, LASTUPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE, HIST_CREATEDON)
VALUES (1, 1, 'user1', 1, 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL, CURRENT_TIMESTAMP); 