INSERT INTO SECURITY_FUNCTIONALROLE (FUNCTIONALROLEID, CODE, NAME, DEPARTMENT, ROLE, USERTYPE, ISREADWRITE, ISACTIVE, CREATEDBY, CREATEDON, UPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 'ADMIN', 'Administrator', 'IT', 'ADMIN', 'EMPLOYEE', 1, 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_GROUP (GROUPID, CODE, NAME, ISACTIVE, CREATEDBY, CREATEDON, UPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 'GRP1', 'Group One', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_GROUPMAP (GROUPMAPID, GROUPID, GROUPMAPVALUE, GROUPMAPDESC, EXCLUDE, SORT, ISACTIVE, CREATEDBY, CREATEDON, UPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 1, 'MAP1', 'Map Desc', 0, 1, 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_FUNCTIONALROLEXREF (FUNCTIONALROLEXREFID, FUNCTIONALROLEID, XREFVALUE, ISACTIVE, CREATEDBY, CREATEDON, UPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 1, 'XREF1', 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_USERENTITLEMENTXREF (USERENTITLEMENTXREFID, USERID, ENTITLEMENTID, ISACTIVE, CREATEDBY, CREATEDON, LASTUPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE)
VALUES (1, 'user1', 1, 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL);

INSERT INTO SECURITY_USERENTXREFHIST (USERENTITLEMENTXREFHISTID, USERENTITLEMENTXREFID, USERID, ENTITLEMENTID, ISACTIVE, CREATEDBY, CREATEDON, LASTUPDATEDBY, UPDATEDON, EFFECTIVEDATE, EXPIRYDATE, HIST_CREATEDON)
VALUES (1, 1, 'user1', 1, 1, 'system', CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, CURRENT_DATE, NULL, CURRENT_TIMESTAMP); 

CREATE SEQUENCE IF NOT EXISTS SECURITY_APPLICATION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SECURITY_USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SECURITY_ROLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SECURITY_USER_ROLE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SECURITY_FUNCTIONAL_ROLE_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO SECURITY_APPLICATION (APPLICATION_ID, CODE, NAME, IS_ACTIVE, CREATED_BY, CREATED_ON)
VALUES (NEXT VALUE FOR SECURITY_APPLICATION_SEQ, 'APP1', 'Application One', 1, 'system', CURRENT_TIMESTAMP);

INSERT INTO SECURITY_USER (USER_ID, USERNAME, EMAIL, USER_TYPE, DEPARTMENT, IS_ACTIVE, CREATED_BY, CREATED_ON)
VALUES (NEXT VALUE FOR SECURITY_USER_SEQ, 'user1', 'user1@email.com', 'EMPLOYEE', 'IT', 1, 'system', CURRENT_TIMESTAMP);

INSERT INTO SECURITY_ROLE (ROLE_ID, ROLE_NAME, IS_READ_WRITE, DEPARTMENT, USER_TYPE, IS_ACTIVE, CREATED_BY, CREATED_ON)
VALUES (NEXT VALUE FOR SECURITY_ROLE_SEQ, 'ADMIN', 1, 'IT', 'EMPLOYEE', 1, 'system', CURRENT_TIMESTAMP);

INSERT INTO SECURITY_USER_ROLE (USER_ROLE_ID, USER_ID, ROLE_ID, APPLICATION_ID, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_BY, CREATED_ON)
VALUES (NEXT VALUE FOR SECURITY_USER_ROLE_SEQ, 1, 1, 1, CURRENT_DATE, NULL, 'system', CURRENT_TIMESTAMP);

INSERT INTO SECURITY_FUNCTIONAL_ROLE (FUNCTIONAL_ROLE_ID, APPLICATION_ID, ENTITY_TYPE, ENTITY_SUBTYPE, ENTITY_GROUP, ENTITY_ID, IS_ACTIVE, EFFECTIVE_DATE, EXPIRY_DATE, CREATED_BY, CREATED_ON)
VALUES (NEXT VALUE FOR SECURITY_FUNCTIONAL_ROLE_SEQ, 1, 'TYPE1', 'SUBTYPE1', 'GROUP1', 1, 1, CURRENT_DATE, NULL, 'system', CURRENT_TIMESTAMP); 